export const mockEmployees = [
  {
    id: 1,
    date: "13/01",
    name: "Aisha Doe",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    initials: "AD",
    role: "HR Manager",
    department: "HR",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:00 PM",
    overTime: "1h",
  },
  {
    id: 2,
    date: "13/01",
    name: "Ahmed Khan",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    initials: "AK",
    role: "Software Engineer",
    department: "IT",
    employmentType: "Full-Time",
    status: "Late",
    checkIn: "09:25 AM",
    checkOut: "05:15 PM",
    overTime: "0h",
  },
  {
    id: 3,
    date: "13/01",
    name: "Fatima Ali",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    initials: "FA",
    role: "Marketing Specialist",
    department: "Marketing",
    employmentType: "Full-Time",
    status: "Absent",
    checkIn: "-",
    checkOut: "-",
    overTime: "0h",
  },
  {
    id: 4,
    date: "13/01",
    name: "Bilal Hassan",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    initials: "BH",
    role: "Sales Executive",
    department: "Sales",
    employmentType: "Part-Time",
    status: "Present",
    checkIn: "10:00 AM",
    checkOut: "03:00 PM",
    overTime: "0.5h",
  },
  {
    id: 5,
    date: "13/01",
    name: "Sana Raza",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    initials: "SR",
    role: "Designer",
    department: "Design",
    employmentType: "Full-Time",
    status: "Late",
    checkIn: "09:15 AM",
    checkOut: "05:30 PM",
    overTime: "0.5h",
  },
  {
    id: 6,
    date: "13/01",
    name: "Usman Tariq",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    initials: "UT",
    role: "Developer",
    department: "IT",
    employmentType: "Part-Time",
    status: "Present",
    checkIn: "11:00 AM",
    checkOut: "04:00 PM",
    overTime: "0h",
  },
  {
    id: 7,
    date: "13/01",
    name: "Hina Iqbal",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    initials: "HI",
    role: "Content Writer",
    department: "Marketing",
    employmentType: "Full-Time",
    status: "Absent",
    checkIn: "-",
    checkOut: "-",
    overTime: "0h",
  },
  {
    id: 8,
    date: "13/01",
    name: "Owais Malik",
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    initials: "OM",
    role: "Support Executive",
    department: "Support",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:05 AM",
    checkOut: "05:10 PM",
    overTime: "0.5h",
  },
  {
    id: 9,
    date: "13/01",
    name: "Maryam Shah",
    avatar: "https://randomuser.me/api/portraits/women/9.jpg",
    initials: "MS",
    role: "HR Assistant",
    department: "HR",
    employmentType: "Part-Time",
    status: "Late",
    checkIn: "10:30 AM",
    checkOut: "03:20 PM",
    overTime: "0h",
  },
  {
    id: 10,
    date: "13/01",
    name: "Ali Raza",
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    initials: "AR",
    role: "Manager",
    department: "Sales",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:00 PM",
    overTime: "1h",
  },
  {
    id: 11,
    date: "13/01",
    name: "Sofia Khan",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
    initials: "SK",
    role: "Designer",
    department: "Design",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:10 AM",
    checkOut: "05:20 PM",
    overTime: "0.5h",
  },
  {
    id: 12,
    date: "13/01",
    name: "Hamza Ali",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    initials: "HA",
    role: "Software Engineer",
    department: "IT",
    employmentType: "Full-Time",
    status: "Absent",
    checkIn: "-",
    checkOut: "-",
    overTime: "0h",
  },
  {
    id: 13,
    date: "13/01",
    name: "Noor Fatima",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
    initials: "NF",
    role: "Content Writer",
    department: "Marketing",
    employmentType: "Part-Time",
    status: "Present",
    checkIn: "10:05 AM",
    checkOut: "03:05 PM",
    overTime: "0h",
  },
  {
    id: 14,
    date: "13/01",
    name: "Zain Malik",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    initials: "ZM",
    role: "Developer",
    department: "IT",
    employmentType: "Full-Time",
    status: "Late",
    checkIn: "08:55 AM",
    checkOut: "05:05 PM",
    overTime: "0h",
  },
  {
    id: 15,
    date: "13/01",
    name: "Ayesha Tariq",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    initials: "AT",
    role: "HR Manager",
    department: "HR",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:15 PM",
    overTime: "0.5h",
  },
  {
    id: 16,
    date: "13/01",
    name: "Imran Shah",
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
    initials: "IS",
    role: "Sales Executive",
    department: "Sales",
    employmentType: "Part-Time",
    status: "Absent",
    checkIn: "-",
    checkOut: "-",
    overTime: "0h",
  },
  {
    id: 17,
    date: "13/01",
    name: "Sara Ali",
    avatar: "https://randomuser.me/api/portraits/women/17.jpg",
    initials: "SA",
    role: "Marketing Specialist",
    department: "Marketing",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:05 AM",
    checkOut: "05:05 PM",
    overTime: "0.5h",
  },
  {
    id: 18,
    date: "13/01",
    name: "Tariq Khan",
    avatar: "https://randomuser.me/api/portraits/men/18.jpg",
    initials: "TK",
    role: "Developer",
    department: "IT",
    employmentType: "Full-Time",
    status: "Late",
    checkIn: "08:50 AM",
    checkOut: "05:10 PM",
    overTime: "0h",
  },
  {
    id: 19,
    date: "13/01",
    name: "Hira Shah",
    avatar: "https://randomuser.me/api/portraits/women/19.jpg",
    initials: "HS",
    role: "Designer",
    department: "Design",
    employmentType: "Part-Time",
    status: "Present",
    checkIn: "10:00 AM",
    checkOut: "03:00 PM",
    overTime: "0h",
  },
  {
    id: 20,
    date: "13/01",
    name: "Omar Raza",
    avatar: "https://randomuser.me/api/portraits/men/20.jpg",
    initials: "OR",
    role: "Support Executive",
    department: "Support",
    employmentType: "Full-Time",
    status: "Absent",
    checkIn: "-",
    checkOut: "-",
    overTime: "0h",
  },
  {
    id: 21,
    date: "13/01",
    name: "Fatima Noor",
    avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    initials: "FN",
    role: "HR Assistant",
    department: "HR",
    employmentType: "Full-Time",
    status: "Late",
    checkIn: "09:20 AM",
    checkOut: "05:10 PM",
    overTime: "0h",
  },
  {
    id: 22,
    date: "13/01",
    name: "Ali Hassan",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    initials: "AH",
    role: "Manager",
    department: "Sales",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:15 PM",
    overTime: "1h",
  },
  {
    id: 23,
    date: "13/01",
    name: "Maryam Tariq",
    avatar: "https://randomuser.me/api/portraits/women/23.jpg",
    initials: "MT",
    role: "Content Writer",
    department: "Marketing",
    employmentType: "Part-Time",
    status: "Present",
    checkIn: "10:00 AM",
    checkOut: "03:10 PM",
    overTime: "0h",
  },
  {
    id: 24,
    date: "13/01",
    name: "Haris Khan",
    avatar: "https://randomuser.me/api/portraits/men/24.jpg",
    initials: "HK",
    role: "Software Engineer",
    department: "IT",
    employmentType: "Full-Time",
    status: "Late",
    checkIn: "08:40 AM",
    checkOut: "05:00 PM",
    overTime: "0h",
  },
  {
    id: 25,
    date: "13/01",
    name: "Sadia Ali",
    avatar: "https://randomuser.me/api/portraits/women/25.jpg",
    initials: "SA",
    role: "Designer",
    department: "Design",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:00 PM",
    overTime: "0.5h",
  },
  {
    id: 26,
    date: "13/01",
    name: "Bilal Raza",
    avatar: "https://randomuser.me/api/portraits/men/26.jpg",
    initials: "BR",
    role: "Developer",
    department: "IT",
    employmentType: "Part-Time",
    status: "Present",
    checkIn: "11:05 AM",
    checkOut: "04:00 PM",
    overTime: "0h",
  },
  {
    id: 27,
    date: "13/01",
    name: "Sania Shah",
    avatar: "https://randomuser.me/api/portraits/women/27.jpg",
    initials: "SS",
    role: "Marketing Specialist",
    department: "Marketing",
    employmentType: "Full-Time",
    status: "Absent",
    checkIn: "-",
    checkOut: "-",
    overTime: "0h",
  },
  {
    id: 28,
    date: "13/01",
    name: "Omar Ali",
    avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    initials: "OA",
    role: "Support Executive",
    department: "Support",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:10 PM",
    overTime: "0.5h",
  },
  {
    id: 29,
    date: "13/01",
    name: "Areeba Khan",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    initials: "AK",
    role: "HR Assistant",
    department: "HR",
    employmentType: "Part-Time",
    status: "Late",
    checkIn: "10:15 AM",
    checkOut: "03:15 PM",
    overTime: "0h",
  },
  {
    id: 30,
    date: "13/01",
    name: "Zubair Malik",
    avatar: "https://randomuser.me/api/portraits/men/30.jpg",
    initials: "ZM",
    role: "Manager",
    department: "Sales",
    employmentType: "Full-Time",
    status: "Present",
    checkIn: "09:00 AM",
    checkOut: "05:30 PM",
    overTime: "1h",
  },
];
